# Generated by Django 4.0.5 on 2022-08-01 20:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('removed_on', models.DateTimeField(blank=True, null=True)),
                ('category', models.PositiveSmallIntegerField(choices=[(200, 'Movie'), (300, 'TV Show'), (400, 'Book'), (500, 'Music'), (600, 'Restaurant')], default=100)),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('external_rating', models.DecimalField(decimal_places=2, help_text='The rating this piece has in the real-world, based on whatever platform it comes from, not from users on the site. Ranges from 0-10 with up to 2 decimal places only. Not all sites use a scale out of 10, which is why we allow some decimals for the conversion; 4.33/5 => 8.67/10.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('removed_on', models.DateTimeField(blank=True, null=True)),
                ('followed_on', models.DateTimeField(blank=True, help_text='The date the receiver completed this recommendation. For example, the date the receiver finished reading the book, or watching the movie.', null=True)),
                ('ignored_on', models.DateTimeField(blank=True, help_text='The date the receiver decided to intentionally ignore this recommendation. Forexample, "I am not going to read that book, sorry Jim."', null=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recs_given', to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.piece')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recs_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('removed_on', models.DateTimeField(blank=True, null=True)),
                ('score', models.SmallIntegerField(help_text='The rating the recommendation receiver is giving this recommendation. The site requires that all ratings be out of 10, and whole numbers only.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.recommendation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
