# Generated by Django 4.0.5 on 2022-08-15 21:43

from django.db import migrations, models
import recommendations.models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=recommendations.models.select_storage, upload_to=recommendations.models.image_filename),
        ),
    ]
